schema_version: 1

context:
  name: ecape
  version: "0.1.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/ecape-${{ version }}.tar.gz
  sha256: df31ec798fe4b00bfcf1c3863f7f839775fafd6525147d21b641f55758aeb1b3

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - metpy >=1.2.0
    - numpy >=1.21.0
    - pytest

tests:
  - python:
      imports:
        - ecape
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  summary: Calculate the entraining CAPE (ECAPE) of a parcel.
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/citylikeamradio/ecape
  repository: https://github.com/citylikeamradio/ecape

extra:
  recipe-maintainers:
    - akrherz
